# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ceda_theme_mezzanine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('background', mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Background Image')),
                ('heading', models.CharField(blank=True, max_length=100)),
                ('subheading', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, help_text=b'Add <br> for line breaks')),
                ('button_text', models.CharField(blank=True, help_text=b'Optional, if present a button with the link specified below will be in the slide', max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=2000)),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Image')),
                ('custom', models.TextField(blank=True, help_text=b'Create a custom slide, everything else will be overriden')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='ceda_theme_mezzanine.HomePage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
    ]
