# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceda_theme_mezzanine', '0002_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='background',
        ),
    ]
