# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 10:23
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ceda_theme_mezzanine', '0003_remove_slide_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='content',
            field=mezzanine.core.fields.RichTextField(blank=True, help_text=b'Brief introduction to Portfolio'),
        ),
    ]
